{if !empty($coupon_blocks.popular_shops)}
	<div class="owl-carousel sl-shops">
		{foreach $coupon_blocks.popular_shops as $popular_shop}
			<div class="sl-shops__item">
				<a href="{ia_url type='url' item='shops' data=$popular_shop}" class="shop-thumbnail">
					{if $popular_shop.shop_image}
						{ia_image file=$popular_shop.shop_image.path title=$popular_shop.title|escape:'html' width='150' height='150'}
					{else}
						<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$popular_shop.website}" alt="Generated by WebThumbnail.org">
					{/if}
				</a>
				<h5><a href="{ia_url type='url' item='shops' data=$popular_shop}">{$popular_shop.title}</a></h5>
				<p>{$popular_shop.description|strip_tags|truncate:80:'...'}</p>
			</div>
		{/foreach}
	</div>

	{ia_print_js files='_IA_TPL_owl.carousel.min'}
	{ia_add_js}
$(function() {
	$('.sl-shops').owlCarousel({
		nav: false,
		dots: true,
		margin: 15,
		loop: true,
		autoplay: true,
		responsive: {
			0: {
				items: 2
			},
			500: {
				items: 3
			},
			750: {
				items: 4
			},
			900: {
				items: 6
			}
		}
	});
});
	{/ia_add_js}
{/if}